function createPDF(obj)

%%
Margin  = 2;
szPage  = [21 29.7];
szInner = szPage - 2 * Margin;

hFig = figure( ...
    'Visible',              'off', ...
    'Units',                'centimeters', ...
    'PaperUnits',           'centimeters', ...
    'PaperSize',            szPage, ...
    'InnerPosition',        [0 0 szInner], ...
    'PaperPosition',        [Margin Margin szInner], ...
    'InvertHardcopy',       'on');

hAx.Title = axes(hFig, ...
    'Units',                'centimeters', ...
    'Position',             [0 szInner(2)-1 szInner(1) 1], ...
    'Visible',              'off', ...
    'Box',                  'on');
text(hAx.Title,.5,1,{'\bfIntrinsic Optical Imaging\rm',datestr(now,'yyyy-mm-dd HH:MM')}, ...
    'HorizontalAlignment',  'center', ...
    'VerticalAlignment',    'top', ...
    'Interpreter',          'tex')


szImage = (szInner(1)-1)/2 * [1 obj.Parent.Red.Size(2)/obj.Parent.Red.Size(1)];

hAx.Image(1) = axes(hFig, ...
	'Units',                'centimeters', ...
	'InnerPosition',        [0 szInner(2)-szImage(2)-3 szImage(1) szImage(2)]);
hAx.Image(2) = axes(hFig, ...
	'Units',                'centimeters', ...
	'InnerPosition',        [szInner(1)/2+0.5 szInner(2)-szImage(2)-3 szImage(1) szImage(2)]);
hIm(1) = image(hAx.Image(1),obj.Parent.Green.RGB);
hIm(2) = image(hAx.Image(2),obj.Parent.Red.RGB);

set(hAx.Image, ...
    'XTick',                [], ...
    'YTick',                [], ...
    'XColor',               'none', ...
    'YColor',               'none');
title(hAx.Image(1),'Anatomy')
title(hAx.Image(2),'\DeltaF/F')

sb(1) = scalebar(hAx.Image(1),obj.P.Scale.PxPerCm);
sb(2) = scalebar(hAx.Image(2),obj.P.Scale.PxPerCm / obj.P.Camera.Binning);
set(sb,...
    'FontSize', 8, ...
    'BarSize',  [60 2], ...
    'Margin',   5, ...
    'Padding',  1);

hAx.Temporal = axes(hFig, ...
    'Units',                'centimeters', ...
    'OuterPosition',        [0 hAx.Image(1).Position(2)-5 szImage(1) 4]);


print(hFig,'-dpdf','test.pdf')
close(hFig)