function createPDF(obj)

%%
Margin  = 2;
szPage  = [21 29.7];
szInner = szPage - 2 * Margin;
szImage = (szInner(1)-1)/2 * [1 obj.Parent.Red.Size(2)/obj.Parent.Red.Size(1)];
hTitle  = 1;
hTemp   = 5;
hStim   = 2;

f = figure( ...
    'Visible',              'off', ...
    'Units',                'centimeters', ...
    'PaperUnits',           'centimeters', ...
    'PaperSize',            szPage, ...
    'InnerPosition',        [0 0 szInner+Margin*2], ...
    'PaperPosition',        [0 0 szInner+Margin*2]);

% Headings
ax.Title = axes(f, ...
    'Units',                'centimeters', ...
    'Position',             [Margin szInner(2)+Margin-hTitle szInner(1) hTitle], ...
    'Visible',              'off');
text(ax.Title,.5,1,{'\bfIntrinsic Optical Imaging\rm',...
    datestr(obj.Trials(1).TimestampDAQ,'yyyy-mm-dd HH:MM')}, ...
    'HorizontalAlignment',  'center', ...
    'VerticalAlignment',    'top', ...
    'Interpreter',          'tex')

% Images
ax.Image(1) = axes(f, ...
	'Units',                'centimeters', ...
	'InnerPosition',        [Margin ax.Title.Position(2)-szImage(2)-3 szImage(1:2)]);
ax.Image(2) = axes(f, ...
	'Units',                'centimeters', ...
	'InnerPosition',        [szInner(1)/2+0.5+Margin ax.Title.Position(2)-szImage(2)-3 szImage(1:2)]);
im(1) = image(ax.Image(1),obj.Parent.Green.RGB);
im(2) = image(ax.Image(2),obj.Parent.Red.RGB);
set(ax.Image, ...
    'XTick',                [], ...
    'YTick',                [], ...
    'XColor',               'none', ...
    'YColor',               'none', ...
    'Nextplot',             'add');
title(ax.Image(1),'Histology / Vasculature')
title(ax.Image(2),'Intrinsic Signal (\DeltaF/F)')

% Plot ROI markers
plot(ax.Image(2),...
    obj.Parent.Red.Line.XData,obj.Parent.Red.Line.YData,'k',...
    'LineWidth',            .75);
point(1) = scatter(ax.Image(1),...
    obj.Parent.Red.Center(1) * obj.P.Camera.Binning, ...
    obj.Parent.Red.Center(2) * obj.P.Camera.Binning,10);
point(2) = scatter(ax.Image(2),...
    obj.Parent.Red.Center(1),obj.Parent.Red.Center(2),10);
set(point, ...
    'MarkerEdgeColor',      'k', ...
    'MarkerFaceColor',      'r', ...
    'LineWidth',            .75)

% Scalebars
sb(1) = scalebar(ax.Image(1),obj.P.Scale.PxPerCm);
sb(2) = scalebar(ax.Image(2),obj.P.Scale.PxPerCm / obj.P.Camera.Binning);
set(sb,...
    'FontSize', 8, ...
    'BarSize',  [60 2], ...
    'Margin',   5, ...
    'Padding',  1);

% hAx.Temporal = copyobj(obj.Parent.h.axes.temporal,hFig);
% set(hAx.Temporal, ...
%     'Units',                'centimeters', ...
%     'InnerPosition',        [0 hAx.Image(1).Position(2)-6 szImage(1) 4]);

ax.Temporal = axes(f, ...
    'Units',                'centimeters', ...
    'InnerPosition',        [ax.Image(1).Position(1) ax.Image(1).Position(2)-hTemp-1 szImage(1) hTemp], ...
    'TickDir',              'out', ...
    'XColor',               'none', ...
    'FontSize',             8);
ax.Stimulus = axes(f, ...
    'Units',                'centimeters', ...
    'InnerPosition',        [ax.Image(1).Position(1) ax.Temporal.Position(2)-hStim-1 szImage(1) hStim], ...
    'TickDir',              'out', ...
    'NextPlot',             'add', ...
    'FontSize',             8);
ax.Spatial = axes(f, ...
    'Units',                'centimeters', ...
    'InnerPosition',        [ax.Image(2).Position(1) ax.Temporal.Position(2)-hStim-hTemp-1 szImage(1) hStim+hTemp+1], ...
    'TickDir',              'out', ...
    'NextPlot',             'add', ...
    'FontSize',             8);
linkaxes([ax.Temporal ax.Stimulus],'x')

tmp = obj.Parent.Stimulus.generate(obj.P.Stimulus);
plot(ax.Stimulus,tmp.Time,tmp.Data,'k','LineWidth',0.5)
xlim(ax.Stimulus,tmp.Time([1 end]))
ylim(ax.Stimulus,[0 obj.Parent.Stimulus.Amplitude])
xlabel(ax.Stimulus,'Time (s)')
ylabel(ax.Stimulus,'Stimulus (V)')

print(f,'-dpdf','test.pdf')
close(f)