function varargout = save2tiff(obj,data,timestamp)

% Filename
fn = sprintf('%03d_%s.tif',obj.n,...
    datestr(timestamp,'yymmdd_HHMMSS'));
obj.Parent.message('Saving image data to disk: %s',fn)

% TIFF options
options = struct( ...
    'ImageWidth',          size(data,2), ...
    'ImageLength',         size(data,1), ...
    'Photometric',         Tiff.Photometric.MinIsBlack, ...
    'Compression',         Tiff.Compression.LZW, ...
    'PlanarConfiguration', Tiff.PlanarConfiguration.Chunky, ...
    'BitsPerSample',       16, ...
    'SamplesPerPixel',     size(data,3), ...
    'XResolution',         round(obj.Parent.Scale.PxPerCm), ...
    'YResolution',         round(obj.Parent.Scale.PxPerCm), ...
    'ResolutionUnit',      Tiff.ResolutionUnit.Centimeter, ...
    'Software',            ['Intrinsic Imaging ' intrinsic.version], ...
    'Make',                obj.P.Camera.Adaptor, ...
    'Model',               obj.P.Camera.DeviceName, ...
    'DateTime',            datestr(timestamp,'yyyy:mm:dd HH:MM:SS'), ...
    'ImageDescription',    sprintf(['ImageJ=\nimages=%d\nframes=%d\n' ...
        'slices=1\nhyperstack=false\nunit=cm\nfinterval=%0.5f\n' ...
        'fps=%0.5f\n'],size(data,4),size(data,4),...
        1/obj.P.Camera.FrameRate,obj.P.Camera.FrameRate), ...
    'SampleFormat',        Tiff.SampleFormat.UInt, ...
    'RowsPerStrip',        512);

% Save to TIFF
tiff = Tiff(fullfile(obj.DirTemp,fn),'w');
for frame = 1:size(data,4)
    tiff.setTag(options);
    tiff.write(data(:, :, :, frame));
    if frame < size(data,4)
        tiff.writeDirectory();
    end
end
tiff.close()

% Return filename (optionally)
if nargout > 0
    varargout{1} = fn;
end