function createPDF(fn)

%%
PageSize    = [21 29.7];
Margin      = 2;
InnerSize   = PageSize - 2*Margin;

hFig = figure( ...
    'Visible',              'off', ...
    'Units',                'centimeters', ...
    'PaperUnits',           'centimeters', ...
    'PaperSize',            PageSize, ...
    'InnerPosition',        [0 0 InnerSize], ...
    'PaperPosition',        [Margin Margin InnerSize], ...
    'InvertHardcopy',       'on');

get(hFig)



hAx.Title = axes(hFig, ...
    'Units',                'centimeters', ...
    'Position',             [0 InnerSize(2)-1 InnerSize(1) 1], ...
    'Visible',              'off', ...
    'Box',                  'on');
text(hAx.Title,.5,1,{'\bfIntrinsic Optical Imaging\rm',datestr(now,'yyyy-mm-dd HH:MM')}, ...
    'HorizontalAlignment',  'center', ...
    'VerticalAlignment',    'top', ...
    'Interpreter',          'tex')



testimage = round(rand(1024,1024)*256);
imageSize = size(testimage);
wImage = (InnerSize(1) - 1) / 2;
hImage = wImage * imageSize(2)/imageSize(1);
greenImage = ind2rgb(testimage,gray());
redImage = ind2rgb(testimage,flipud(brewermap(256,'PuOr')));

hAx.Green = axes(hFig, ...
    'Units',                'centimeters', ...
    'InnerPosition',        [0 InnerSize(2)-hImage-3 wImage hImage], ...
    'Visible',              'off');
image(hAx.Green,greenImage);
title(hAx.Green,'Anatomy')
set(hAx.Green, ...
    'XTick',                [], ...
    'YTick',                [])
scalebar(hAx.Green,200);

hAx.Red = axes(hFig, ...
    'Units',                'centimeters', ...
    'InnerPosition',        [InnerSize(1)/2+0.5 InnerSize(2)-hImage-3 wImage hImage], ...
    'Visible',              'off');
image(hAx.Red,redImage);
title(hAx.Red,'Activity Map')
set(hAx.Red, ...
    'XTick',                [], ...
    'YTick',                [])
scalebar(hAx.Red,200);



hAx.Temporal = axes(hFig, ...
    'Units',                'centimeters', ...
    'OuterPosition',        [0 hAx.Green.Position(2)-5 wImage 4]);


print(hFig,'-dpdf','test.pdf')
close(hFig)