function GUIgeneric(obj,name,margin,bottom)

imsize  = obj.ROISize*obj.Scale;        % image size [px]
psize   = imsize+4;                     % panel size [px]
if bottom > 0                           % figure size [px]
    fsize   = psize+[2 3]*margin+[0 bottom];
    ppos    = [margin+1 2*margin+bottom psize];
else
    fsize   = psize+2*margin;
    ppos    = [margin+1 margin psize];
end

obj.h.fig.(lower(name)) = figure( ...
    'Visible',          'off', ...
    'Toolbar',          'none', ...
    'Menu',             'none', ...
    'NumberTitle',      'off', ...
    'Resize',           'off', ...
    'DockControls',     'off', ...
    'Position',         [5 5 fsize], ...
    'Tag',              name, ...
    'Name',             [name ' Image'], ...
    'CloseRequestFcn',  {@(obj,~) set(obj,'visible','off')});
obj.h.panel.(lower(name)) = uipanel(obj.h.fig.(lower(name)), ...
    'Units',            'Pixels', ...
    'BorderType',       'beveledin', ...
    'Position',         ppos, ...
    'Tag',              name, ...
    'BackgroundColor',  'black');
obj.h.axes.(lower(name)) = axes(...
    'Parent',           obj.h.panel.(lower(name)), ...
    'Position',         [0 0 1 1], ...
    'Tag',              name, ...
    'DataAspectRatio',  [1 1 1], ...
    'CLimMode',         'manual', ...
    'Clim',             [0 obj.VideoBits-1]);

if strcmpi(name,'green')
    tmp = obj.ROISize * obj.Binning;
else
    tmp = obj.ROISize;
end

obj.h.image.(lower(name)) = imshow(zeros(fliplr(tmp)),...
    'DisplayRange',     [0 obj.VideoBits-1], ...
    'Parent',           obj.h.axes.(lower(name)));