function plotStimulus(obj,p)

if ~exist('p','var')
    ts = obj.DAQ.OutputData.Stimulus;
    p  = obj.Stimulus.Parameters;
else
    ts = obj.Stimulus.generate(p);
end

set(obj.h.plot.stimulus, ...
    'XData',    ts.Time, ...
    'YData',    ts.Data);
set(obj.h.axes.stimulus, ...
    'XLim',     [-p.PreStimulus p.Duration+p.PostStimulus], ...
    'YLim',     [0 p.Amplitude], ...
    'YTick',    [0 p.Amplitude]);