function varargout = setup(obj)
% open GUI to change camera settings.

nargoutchk(0,1)

% create settings window & panels
window     = settingsWindow('Name','Camera Settings','Width',270);
obj.Figure = window.Handle;
panel(1)   = window.addPanel('Title','Device Selection');
panel(2)   = window.addPanel('Title','Resolution & ROI');
panel(3)   = window.addPanel('Title','Timing');

% create UI controls
controls.adaptor = panel(1).addPopupmenu( ...
    'Label',   	'Adaptor', ...
    'Callback',	@obj.cbAdapt, ...
    'String',  	[{'none'} eval('imaqhwinfo').InstalledAdaptors]);
controls.adaptor.Value = max([find(strcmp(controls.adaptor.String,...
    loadVar(obj,'adaptor',''))) 1]);
controls.device = panel(1).addPopupmenu( ...
    'Label',   	'Device', ...
    'Callback',	@obj.cbDevice);
controls.mode = panel(2).addPopupmenu( ...
    'Label',   	'Mode', ...
    'Callback',	@obj.cbMode);
controls.res = panel(2).addEditXY( ...
    'Label',    'Resolution (px)', ...
    'Enable',   'off');
controls.binning = panel(2).addEditXY( ...
    'Label',    'Hardware Binning', ...
    'Enable',   'off');
controls.ROI = panel(2).addEditXY( ...
    'Label',    'ROI (px)', ...
    'Callback', @obj.cbROI);
controls.FPS = panel(3).addEdit( ...
    'Label',   	'Frame Rate (Hz)', ...
    'Callback',	@obj.cbFPS);
controls.bitRate = panel(3).addEdit( ...
    'Label',   	'Bit Rate (Mbit/s)', ...
    'Enable',   'off');
[controls.okay,controls.cancel] = window.addOKCancel(...
    'Callback',	@obj.cbOkay);

% save appdata & initialize
setappdata(obj.Figure,'controls',controls);
obj.cbAdapt()
window.Visible = 'on';

% output arguments
if nargout
    varargout{1} = obj.Figure;
end
