function varargout = setup(obj)
% open GUI to change camera settings.

nargoutchk(0,1)

% create settings window & panels
window     = settingsWindow('Name','Stimulus Settings','Width',260);
obj.Figure = window.Handle;
panel(1)   = window.addPanel('Title','Waveform');
panel(2)   = window.addPanel('Title','Timing');

% create UI controls
Controls.Type = panel(1).addPopupmenu( ...
    'Label',   	'Waveform Type', ...
    'Callback',	@obj.generateWaveform, ...
    'String',  	{'Sinusoidal', 'Triangular', 'Square'});
Controls.Type.Value = max([find(strcmp(Controls.Type.String,...
    obj.WaveformType)) 1]);
Controls.Frequency = panel(1).addEdit( ...
    'Label',   	'Frequency (Hz)', ...
    'Callback',	@obj.cbFrequency, ...
    'String',	obj.Frequency);
Controls.DutyCycle = panel(1).addEdit( ...
    'Label',   	'Duty Cycle (%)', ...
    'Callback',	@obj.cbDutyCycle, ...
    'String',	obj.DutyCycle);
Controls.DutyCycle = panel(1).addEdit( ...
    'Label',   	'Ramp (%)', ...
    'Callback',	@obj.cbRamp, ...
    'String',	obj.Ramp);
Controls.DutyCycle = panel(1).addEdit( ...
    'Label',   	'Amplitude (V)', ...
    'Callback',	@obj.cbAmplitude, ...
    'String',	obj.Amplitude);
Controls.Duration = panel(2).addEdit( ...
    'Label',   	'Duration (s)', ...
    'Callback',	@obj.cbDuration, ...
    'String',	obj.Duration);
Controls.PreStimulus = panel(2).addEdit( ...
    'Label',   	'Pre-Stimulus (s)', ...
    'Callback',	@obj.cbPreStimulus, ...
    'String',	obj.PreStimulus);
Controls.PostStimulus = panel(2).addEdit( ...
    'Label',   	'Post-Stimulus (s)', ...
    'Callback',	@obj.cbPostStimulus, ...
    'String',	obj.PostStimulus);
Controls.InterStimulus = panel(2).addEdit( ...
    'Label',   	'Inter-Stimulus (s)', ...
    'Callback',	@obj.cbInterStimulus, ...
    'String',	obj.InterStimulus);
[Controls.okay,Controls.cancel] = window.addOKCancel(...
    'Callback',	@obj.cbOkay);

% save appdata & initialize
setappdata(obj.Figure,'controls',Controls);
window.Visible = 'on';

obj.Parent.h.axes.temporalBg.Visible = 'off';
obj.Parent.h.axes.temporal.Visible = 'on';

% output arguments
if nargout
    varargout{1} = obj.Figure;
end
