function varargout = setup(obj)
% open GUI to change scale settings.

nargoutchk(0,1)
deviceData = obj.DeviceData;

% create settings window & panels
window = settingsWindow(...
    'WindowStyle',  'normal', ...
    'Visible',      'off', ...
    'Name',         'Scale Settings', ...
    'Position',     [100 100 250 10]);
panel(1) = window.addPanel( ...
    'Title',        'Camera');
panel(2) = window.addPanel( ...
    'Title',        'Microscope');

% create UI controls
controls.adaptor = panel(1).addEdit( ...
    'Label',        'Adaptor', ...
    'String',       obj.Camera.Adaptor, ...
    'Enable',       'off');
controls.camera = panel(1).addEdit( ...
    'Label',        'Device', ...
    'String',       obj.Camera.DeviceName, ...
    'Enable',       'off');
controls.mode = panel(1).addEdit( ...
    'Label',        'Mode', ...
    'String',       obj.Camera.Mode, ...
    'Enable',       'off');
controls.magnification = panel(2).addPopupEdit( ...
    'Label',        'Magnification', ...
    'Callback',     @obj.cbMagnification, ...
    'String',       obj.Magnifications, ...
    'Value',        find(ismember(obj.Magnifications,obj.Magnification))); %#ok<FNDSB>
controls.pxpercm = panel(2).addEdit( ...
    'Label',        'Pixels per cm', ...
    'String',       '', ...
    'Enable',       'off');
controls.calibrate = panel(2).addButton( ...
    'Label',        '', ...
    'Callback',     @obj.cbCalibrate, ...
    'String',       'Calibrate');
[controls.okay,controls.cancel] = window.addOKCancel(...
    'Callback',	@obj.cbOkay);
movegui(window.Handle,'center')
window.Visible = 'on';

% store UI control objects
obj.Figure = window.Handle;
setappdata(obj.Figure,'deviceData',deviceData)
setappdata(obj.Figure,'controls',controls);

% initialize
obj.cbMagnification()

% output arguments
if nargout == 1
    varargout{1} = obj.Figure;
end