function varargout = setup(obj)
% open GUI to change DAQ settings.

nargoutchk(0,1)

% create controls
sw = settingsWindow(...
    'WindowStyle',  'normal', ...
    'Visible',      'off', ...
    'Name',         'Scale Settings', ...
    'Position',     [100 100 250 10]);
sp = sw.addPanel();
controls.adaptor = sp.addUIControl( ...
    'Style',        'edit', ...
    'Label',        'Adaptor', ...
    'Enable',       'off');
controls.camera = sp.addUIControl( ...
    'Style',        'edit', ...
    'Label',        'Camera', ...
    'Enable',       'off');
controls.mode = sp.addUIControl( ...
    'Style',        'popupmenu', ...
    'Label',        'Mode', ...
    'Callback',     @obj.cbMode, ...
    'String',       obj.Camera.modes);
controls.scale = sp.addUIControl( ...
    'Style',        'popupmenu', ...
    'Label',        'Magnification', ...
    'Callback',     [], ...
    'String',       {'1','2','3'});
[controls.okay,controls.cancel] = sw.addOKCancel();
movegui(sw.Handle,'center')
sw.Visible = 'on';

% store UI control objects
obj.Figure = sw.Handle;
setappdata(obj.Figure,'controls',controls);

% initialize
%obj.cbVendor(ctrl.vendor)

% output arguments
if nargout == 1
    varargout{1} = obj.Figure;
end